"""empty message

Revision ID: b430e552bf77
Revises: efb6cf82880f
Create Date: 2018-11-20 14:10:48.330449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b430e552bf77'
down_revision = 'efb6cf82880f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catequista', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'catequista', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catequista', type_='unique')
    op.alter_column('catequista', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
