"""empty message

Revision ID: efb6cf82880f
Revises: 
Create Date: 2018-11-05 17:04:57.531145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb6cf82880f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diocese', sa.String(length=20), nullable=False),
    sa.Column('paroquia', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('logradouro', sa.String(length=60), nullable=True),
    sa.Column('bairro', sa.String(length=30), nullable=True),
    sa.Column('cidade', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catequista',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('id_comunidade', sa.Integer(), nullable=False),
    sa.Column('tipo1', sa.String(length=20), nullable=False),
    sa.Column('tipo2', sa.String(length=20), nullable=True),
    sa.Column('coordenacao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_comunidade'], ['comunidade.id'], ),
    sa.PrimaryKeyConstraint('id', 'username'),
    sa.UniqueConstraint('id')
    )
    op.create_table('encontro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_comunidade', sa.Integer(), nullable=False),
    sa.Column('ano_turma', sa.String(), nullable=False),
    sa.Column('tema', sa.String(length=30), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('leitura', sa.Text(), nullable=True),
    sa.Column('atividade', sa.Text(), nullable=True),
    sa.Column('compromisso', sa.Text(), nullable=True),
    sa.Column('avisos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_comunidade'], ['comunidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ficha_catequisando',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_comunidade', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('data_nasc', sa.Date(), nullable=False),
    sa.Column('nome_mae', sa.String(length=50), nullable=False),
    sa.Column('nome_pai', sa.String(length=50), nullable=False),
    sa.Column('batizado', sa.String(length=3), nullable=False),
    sa.Column('eucaristia', sa.String(length=3), nullable=True),
    sa.Column('escolaridade', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(length=60), nullable=False),
    sa.Column('bairro', sa.String(length=30), nullable=False),
    sa.Column('cidade', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('numero_casa', sa.String(), nullable=False),
    sa.Column('ponto_referencia', sa.String(), nullable=False),
    sa.Column('telefone1', sa.String(length=15), nullable=False),
    sa.Column('telefone2', sa.String(length=15), nullable=True),
    sa.Column('whatsapp', sa.String(length=15), nullable=True),
    sa.Column('data_inscricao', sa.Date(), nullable=False),
    sa.Column('ano_turma', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_comunidade'], ['comunidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ficha_catequista',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_catequista', sa.Integer(), nullable=False),
    sa.Column('id_comunidade', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=50), nullable=False),
    sa.Column('data_nasc', sa.Date(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('ano_entrada', sa.Integer(), nullable=False),
    sa.Column('escolaridade', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=60), nullable=False),
    sa.Column('bairro', sa.String(length=30), nullable=False),
    sa.Column('cidade', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('numero_casa', sa.String(length=15), nullable=False),
    sa.Column('ponto_referencia', sa.String(length=50), nullable=False),
    sa.Column('crismado', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['id_catequista'], ['catequista.id'], ),
    sa.ForeignKeyConstraint(['id_comunidade'], ['comunidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_catequista')
    )
    op.create_table('frequencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_encontro', sa.Integer(), nullable=False),
    sa.Column('id_catequisando', sa.Integer(), nullable=False),
    sa.Column('presenca', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['id_catequisando'], ['ficha_catequisando.id'], ),
    sa.ForeignKeyConstraint(['id_encontro'], ['encontro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_emissor', sa.Integer(), nullable=False),
    sa.Column('id_comunidade', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('assunto', sa.String(length=20), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_comunidade'], ['comunidade.id'], ),
    sa.ForeignKeyConstraint(['id_emissor'], ['catequista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roteiro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_catequista', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=30), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('data_now', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_catequista'], ['catequista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roteiro')
    op.drop_table('notificacao')
    op.drop_table('frequencia')
    op.drop_table('ficha_catequista')
    op.drop_table('ficha_catequisando')
    op.drop_table('encontro')
    op.drop_table('catequista')
    op.drop_table('comunidade')
    # ### end Alembic commands ###
